
services:
  multi-tennat-app:
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        - DB_URL=postgresql://postgres:password@db:5432/postg
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
    ports:
     - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postg
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postg
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: