
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postg
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: